sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 'stable'
  - '4'
  - '0.12'
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
